### ISSUE TITLE
Подключить SDK amplitude.com в приложение iOS

### ISSUE THREAD

**Issue by CY8ERPUNK1984** [GolosChain/golos-ios#135]
#### Задачи:
 - отслеживать действия пользователя при использовании iOS приложения;
 - исключить из отчетов следующие тестовые аккаунты: 'destroyer2k', 'joseph.kalu', 'nick.lick';
 - на первом этапе подключить следующие 2 метрики:
    1. первая метрика: уникальные заходы в приложение (сколько юзеров зашло в приложение за день, неделю, месяц) - это собирается ивентом на заходы, но из этого потока эвентов нам надо будет вычленять ситуации когда один и тот же юзер 10 раз зашел, и когда 10 юзеров зашли по 1 разу. Это уникальные юзеры за период времени: 
**'ios_login_open' & 'ios_login_close'**
    2. вторая метрика: заход & выход на/из веб-вью регистрации: 
**'webview_ios_screen1_open' & 'webview_ios_screen1_close'**
 - на втором этапе подключить следующие 3 метрики:
     1. первая метрика: заходы на страницу создания нового поста:
**'ios_post_create_open'**
     2. вторая метрика: пост успешно опубликован:
**'ios_post_create_publish'**
     3. третья метрика: написан комментарий:
**'ios_comment_create_publish'**
     4. четвёртая метрика: поставлен лайк:
**'ios_post_like_publish'**
- Формат названий эвентов:
platform_theme_screennumber_about

Пример для iOS
ios_registration_screen1_open
ios_registration_screen2_open
ios_registration_screen3_open
ios_registration_screen4_open
ios_registration_screen5_open

Какие бывают платформы
web_desktop
web_mobile
webview_android
webview_ios
android
ios

[Golos Registration Events](https://docs.google.com/spreadsheets/d/1Ou-s6NwqNErhloOsqyauXw39e5oYmXeFzVAv4S4g_yc/edit?usp=slack&ts=5be2e710)

**New**
- отслеживать открытие приложения ios_app_open

**Comment by Monserg** [comment]
- [x] Выполнено:
 - зарегистрировался на сервисе;
 - создал проект приложения;
 - установил iOS Amplitude SDK;
 - добавил тестовую метку на экране авторизации:
![Events - Amplitude 2018-11-01 19-41-36.png](https://images.zenhubusercontent.com/5b8429634b5806bc2be3f4ac/2d7d7a68-551b-48ba-b672-c25808399c71)
 - создал массив тестовых аккаунтов для исключения из рассылки меток: 'destroyer2k', 'joseph.kalu', 'nick.lick'.

**Comment by Monserg** [comment]
- [x] Выполнено:
 - для CoreData entity User добавил свойство 'isAmplitudeUnique', предназначенное для учета уникальных аккаунтов пользователей iOS App;
 - при очистке кэша для CoreData entity User учитывается значение для свойства 'isAmplitudeUnique';
 - подключил events **'webview_ios_registration_screen1_open'** & **'webview_ios_registration_screen1_close'** для экрана Регистрации ч/з вебвью:
![Events - Amplitude 2018-11-12 14-30-09.png](https://images.zenhubusercontent.com/5b8429634b5806bc2be3f4ac/f742c93d-068d-4565-9d46-afd95aca8323)
 - подключил events **'ios_login_open'** & **'ios_login_close'** для экрана авторизации ч/з мобильное приложение:
![Events - Amplitude 2018-11-12 16-19-46.png](https://images.zenhubusercontent.com/5b8429634b5806bc2be3f4ac/356e07b0-af9a-46ab-9f76-316e10d049d8)
 - подключил events **'ios_post_create_open'** & **'ios_post_create_publish'** для экрана создания поста ч/з мобильное приложение:
![post.png](https://images.zenhubusercontent.com/5b8429634b5806bc2be3f4ac/d4d92655-4461-49f9-b4d8-052f5df3ad9f)
 - подключил events **'ios_comment_create_open' & 'ios_comment_create_publish'** для экрана создания комментария ч/з мобильное приложение:
![comment.png](https://images.zenhubusercontent.com/5b8429634b5806bc2be3f4ac/c6db723f-3104-41fc-87de-965dcfbf15ba)
 - подключил events **'ios_reply_create_open' & 'ios_reply_create_publish'** для экрана создания ответа на комментарий ч/з мобильное приложение:
![reply.png](https://images.zenhubusercontent.com/5b8429634b5806bc2be3f4ac/def39136-41c4-4fb0-b3b9-863da0dda93f)
 - подключил events **'ios_post_like_publish' & 'ios_post_dislike_publish'** для всех возможных экранов ч/з мобильное приложение:
![like.png](https://images.zenhubusercontent.com/5b8429634b5806bc2be3f4ac/6f0f3c6a-d67e-4004-ad58-901db8e2e091)
 - подключил event **'ios_app_open'** для фиксации события по каждому запуску мобильного приложения с учетом 'DEVICE_ID' & 'USER_ID':
![Снимок экрана 2018-11-26 в 11.54.16.png](https://images.zenhubusercontent.com/5b8429634b5806bc2be3f4ac/baa092c0-22db-4158-8514-8df9163f7806)
