### ISSUE TITLE
Дизайн футтера для iPhone X и более новых моделей 

### ISSUE THREAD

**Issue by Monserg** [GolosChain/golos-ios#156]
### Описание:
1. оставить цвет фона для футляра белым или применить для него новое цветовое решение
<img width="251" alt="iphone xs max - 12 1 2018-11-26 08-42-29" src="https://user-images.githubusercontent.com/3746830/48997382-680e8c00-f158-11e8-88d2-70d136c4cfb1.png">
<img width="251" alt="iphone xs max - 12 1 2018-11-26 08-43-21" src="https://user-images.githubusercontent.com/3746830/48997387-6f359a00-f158-11e8-82d3-a0f958c7dd96.png">
<img width="251" alt="iphone xs max - 12 1 2018-11-26 08-43-53" src="https://user-images.githubusercontent.com/3746830/48997391-7361b780-f158-11e8-9c0e-807b70b8ea55.png">

**Comment by kuchinskaya** [comment]
оставить белым
