### ISSUE TITLE
Мелкие правки по iOS

### ISSUE THREAD

**Issue by CY8ERPUNK1984** [GolosChain/golos-ios#163]

**Comment by kuchinskaya** [comment]
1. аватарка в посте вверху пережимается (размер аватарки 30х30рх, отступы сверху и снизу по 9рх)
2. очень мелкий текст в редакторе (сделать 15рх)
3. сложно добавлять теги из-за того, что нет кнопки Return ([добавить кнопку](http://prntscr.com/lri5ce))
[дизайн Add post - text - personal](https://www.figma.com/file/qEqsqNZvfT9aRxQM9tmooO/App-(Copy)?node-id=11169%3A9698)
4. русские теги кажется переводятся на английский (нужно не переводить русские теги)
5. на iPhone XS верхнее меню маленькое и закрывается бровью (опустить текст комментария на 20px ниже)
6. кнопка назад на iPhone XS не работает
   - при написании коммента криво показывает текст
   - меню с выбором ленты плохо работает на iPhone XS
![Image from iOS.png](https://images.zenhubusercontent.com/5bceef19b198c93527505714/4a469f62-0afb-46a5-ad25-59b292a1ecb4)![Image from iOS (1).png](https://images.zenhubusercontent.com/5bceef19b198c93527505714/c4c392f8-f52c-4339-bacf-3a410e7a98fe)![Image from iOS (2).png](https://images.zenhubusercontent.com/5bceef19b198c93527505714/d13649f2-a4fe-43bd-834a-c6c4ba6c2223)![Image from iOS (3).png](https://images.zenhubusercontent.com/5bceef19b198c93527505714/92a7eb83-3cca-4f67-9333-443873f240ab)![Image from iOS (4).png](https://images.zenhubusercontent.com/5bceef19b198c93527505714/746ee8d4-52ce-429c-9852-3e149035873b)

7. при написании коммента криво показывает [текст](http://prntscr.com/lric8g)
8. меню с выбором ленты плохо работает на iPhone XS

**Comment by Monserg** [comment]
- [ ] Исправлено:
   - iPhone 5s: внесены правки на экране Настройки для переключателя "Просмотр картинок";
   - пункт 1: изменена высота панели:
![iPhone XS - 12.1 2018-12-27 11-56-40.png](https://images.zenhubusercontent.com/5b8429634b5806bc2be3f4ac/0e81a5c9-a3d1-46ee-a221-643043556e9d)
   - пункт 2: изменил высоту шрифта с 13 на 15px:
![PostCreateViewController.swift 2018-12-27 13-06-31.png](https://images.zenhubusercontent.com/5b8429634b5806bc2be3f4ac/6eb595c7-7109-49a1-9e1c-f3a9f8223083)
![UITextView+Extensions.swift — Edited 2018-12-27 13-06-11.png](https://images.zenhubusercontent.com/5b8429634b5806bc2be3f4ac/0b6d4ab0-3971-4c0b-b40f-8bf967a76e35)
   - пункт 3 : согласно ТЗ теги создаются по нажатию на пробел:
   - пункт 4: без изменений:
   - пункт 5: исправлено:
![iPhone XS - 12.1 2018-12-27 13-35-55.png](https://images.zenhubusercontent.com/5b8429634b5806bc2be3f4ac/9aba61c3-cc6a-4780-af2a-c746abeae021)
   - пункт 6: :
   - пункт 7: расстояние между Заголовком и текстом поста по дизайну составляет 15px:
![Снимок экрана 2018-12-27 в 13.41.35.png](https://images.zenhubusercontent.com/5b8429634b5806bc2be3f4ac/8e8afd42-4a6b-449c-89f0-84cc7fd999e9)
   - пункт 8: изменена высота панели:
![iPhone XS - 12.1 2018-12-27 12-14-44.png](https://images.zenhubusercontent.com/5b8429634b5806bc2be3f4ac/a26edb67-3d4c-4640-b3a8-475ab43d0d02)

**Comment by Monserg** [comment]
- [x] Ночная тема:
 - внесены правки на основном экране;
 - внесены правки на экране Создание поста;
 - внесены правки на Экранах Посдписчики, Подписки, Проголосовали;
