### ISSUE TITLE
Build 1.0.10 (Release): feedbacks

### ISSUE THREAD

**Issue by Monserg** [GolosChain/golos-ios#25]
Замечания по версии билда

**Comment by Monserg** [comment]
1.
- [x] ошибка авторизации после удачного сканирования QR ключа, возможно это связано, с тем, что по умолчанию введен чужой, логин-пароль.  Убираю его, ввожу свои данные, выскакивает ошибка авторизации. 

     - изменил схему приложения с Release -> Debug, проверил еще раз - проблема не воспроизводится



- [x] Удалить дефолтный введенный логин и пароль.

- [x] не вставляется скопированный приватный ключ 

     - изменена формула на проверку введенного/скопированного значения на первый символ "1" или "5")

2.
- [x] редактор постов не дает публиковать пост и требует выбрать тему. Не должно быть такого условия. Добавлены теги, а редактор не дает публиковать без выбранной темы. 
- [x]  Редактор завис при вводе тега.

     - тег состоит из 1 слова

     - создание нового тега по пробелу

     - приведение введенного названия тега в нижний регистр

     - изменить алгоритм работы по наполнению массива тегами (отслеживать ввод названий без акцента на события клавиатуры)


3.
- [x] убрать кнопки подписаться и написать в Моем профиле

     - скрыл (при возможности можно будет восстановить)


- [x] кнопка выйти на экране профиля не видна при использовании дефолтного кавера. 

     - реализован следующий кейс: по умолчанию надписи и иконки имеют черный цвет, который меняется на белый, если user cover image != nil

- [x] Убрать цифру репутации у юзерпика во всех списках (Лента, Популярное и т.д.) - отказались от этого.

     - скрыл (при необходимости можно будет восстановить)

**Comment by Monserg** [comment]
- [x] проверить загрузку списка постов для разделов "Популярное", "Актуальное", "Новое" и "Промо", не загружаются.

     - изменил схему проекта Release -> Debug (у первой нужно проверить настройки)

**Comment by jevgenika** [comment]
- [x] чужие данные при авторизации остались, не были убраны

     - исправлено 

- [x] вставка постинг ключа и сканирование постинг ключа -выдают ошибку. Войти в приложение удалось лишь свернув приложение и войдя снова.  Желаемый результат войти в приложение при вводе активного ключе обоими способами. Без надобности сворачивать и открывать приложение снова.

     - исправлено 

- [x] ленты пустые, своя лента тоже пустая

     - проверено - исправлена схема приложения с настройками (путь для запросов указывал на пустой тестнет) 

- [ ] на экране создания поста теги введены, при попытки публикации выскакивает сообщение в разработке, не дает публиковать пост

     - АПИ для публикации еще в разработке

**Comment by jevgenika** [comment]
- [x] ленты пустые, данные не приходят
- [x] ошибка авторизации, через раз повторяется,
- [x] в своей ленте показывается свой же пост, один из, не последний. Должен показывать посты подписок.

     - исправлено в build 1.0.14
