### ISSUE TITLE
поправить работу с тегами на экране создания поста

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/golos-ios#26]
- [x] подтянуть поле вводу тегами, сейчас ввод тегов закрыт клавиатурой
- [x] ценрировать текст тега в поле "облака" тега
- [x] не вводить подсказку в поле тега тег 1, тег 2., оставить "облако" пустым
- [x] добавить ввод тега по пробелу

реализовано в build 1.0.12

**Comment by Monserg** [comment]
- добавление нового тега по пробелу реализовано в issuie #25 

- введенные значения сохраняются при переходе на другой экран

- введенные значения удаляются после нажатия на кнопку Отмена

-  для редактора добавил кнопку Done с целью скрывать клавиатуру

**Comment by Monserg** [comment]
реализовано в build 1.0.12

**Comment by jevgenika** [comment]
кнопка скрывать клавиатуру не нужна
