### ISSUE TITLE
реализовать возможности вставки фото в пост

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/golos-ios#27]
на экране создания поста при выборе картинки с девайса картинка не подкрепляется к посту.
- [x] реализовать возможно прикрепить выбранную картинку к посту

при использовании камеры при добавлении фото к посту, фотография добавляется. Вместе с ней добавляется текстовая подсказка. Текст подсказку можно удалить.
- [x] Добавлять фото из камеры без вставки текста по дефолту

реализовано в build 1.0.12

**Comment by Monserg** [comment]
реализовано в build 1.0.12
