### ISSUE TITLE
исправить ошибку получения постов для списков Актуальное, Популярное, Новое и Промо

### ISSUE THREAD

**Issue by Monserg** [GolosChain/golos-ios#28]
списки пустые

реализовано в build 1.0.13

**Comment by Monserg** [comment]
- [x] для работы с данными используется следующий алгоритм: при подключении к Интернету выполняется запрос АПИ к серверу. Полученные данные сохраняются локально в БД. При показе экрана данные запрашиваются из БД и отображаются пользователю. При отсутствии соединения с Интернетом данные сразу запрашиваются из БД

- [x] ошибка пустых списков заключалась в том, что в запросах на получение данных из БД присутствовало ограничение по имени текущего авторизованного пользователя, как дя случая с Лентой постов

**Comment by jevgenika** [comment]
посты в лентах новое, актуальное, популярное отображаются
все посты в лентах отмечены, будто по всем из них были были апвоуты или комменты
- [x] нужно проверить этот момент

**- не исправлено**

     - исправлено в build 1.0.14 #29 

в своей ленте отображается только один пост, пост авторизованного аккаунта
- [x] в своей ленты должны отображаться посты подписок аккаунта

     - исправлено в build 1.0.14 #29

**Comment by Monserg** [comment]
- [x] Исправлено в тикете #69.
