### ISSUE TITLE
баги: Экран 1 вход и авторизация (Welcome & Log in)

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/golos-ios#43]
> **Title-1**: орфографическая ошибка в слове "ключОм"
> 
> **Воспроизведение:**
> 
> 1. открыть приложение
> 2. нажать кнопку "Войти"
> 
> **Результат:** ошибка в заголовке шапки, в кнопке перехода на экран входа с активным ключом. та же ситуация на экране входа с активным ключом
> **Ожидаемый результат:** слово пишется через букву О
- [x] Исправлено:
     - заменил слово 'ключём' -> 'ключом'

- [x] Проверено:

**Comment by Monserg** [comment]
> **Title-2**: текстовка не соответствует требуемой при вводе несуществующего логина
> **Воспроизведение:**
> 
>  1. Открыть приложение.
>   2. Перейти на экран «Войти»
>   3. Ввести логин, которого нет в системе
> 
>  **Postcondition:** ввести приватный ключ в поле приватного ключа, который существует в системе и нажать кнопку «Войти»
> 
>  **Реальный результат:** При вводе неверного логина выдает окно с ошибкой «ошибка авторизации. Если повторится – попробуйте выйти и зайти в свой аккаунт»
>  **Ожидаемый результат:** вход в систему не должен произойти. Должно появиться сообщение в нижнем тулбаре: “Неверный логин или пароль. Попробуйте ввести еще раз”.
- [x] Исправлено:
     - текстовка сообщения исправлена в issue #44.

- [x] Проверено:

**Comment by Monserg** [comment]
> **Title-3**: текстовка не соответствует требуемой при вводе неверного постинг ключа
> **Воспроизведение:**
> 
> 1. Открыть приложение. 
> 2. Перейти на экран «Войти» 
> 3. Ввести в поле ввода приватного ключа ключ, которого нет в системе либо который не соответствует введенному позже логину
> 
> **Postcondition:** ввести существующий логин и нажать кнопку «Войти»
> 
>  **Реальный результат:** После нажатия кнопки «войти» приложение вылетает. После открытия пользователь оказывается авторизованным под тем логином, который ввел
>  **Ожидаемый результат:** вход в систему не должен произойти. Должно появиться сообщение в нижнем тулбаре: “Неверный логин или пароль. Попробуйте ввести еще раз”.
- [x] Исправлено:
     - текстовка сообщения исправлена в issue #44.
- [x] Проверено:
