### ISSUE TITLE
баги: Экран 1.1 вход и авторизация по активному ключу (Log in 2 & active)

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/golos-ios#44]
> **Title-1:** неверная текстовка при вводе логина, который не соответствует введенному активному ключу
> 
> **Воспроизведение:**
> 1. Открыть приложение. 
> 2. Перейти на экран «Войти» 
> 3. Нажать кнопку «Войти с активным ключом»
> 4. Ввести существующий активный ключ 
> 5. Ввести логин, который не соответствует введенному активному ключу 
> 6. Нажать кнопку «Войти»
> 
> **Ожидаемый результат:** вход в систему не должен произойти. Должно появиться сообщение в нижнем тулбаре: “Неверный логин или пароль. Попробуйте ввести еще раз”.
> **Реальный результат:** Появился текст «ошибка авторизации. Если повторится – попробуйте выйти и зайти в свой аккаунт»
- [x] Исправлено: 
     - изменил текстовку

- [x] Проверено:

**Comment by Monserg** [comment]
> **Title-2:** приложение падает после вводе ключа, который не соответствует логину
> 
> **Воспроизведение:**
> 1. Открыть приложение. 
> 2. Перейти на экран «Войти» 
> 3. Нажать кнопку «Войти с активным ключом»
> 4. Ввести существующий логин 
> 5. Ввести активный ключ, который не соответствует введенному ранее логину 
> 6. Нажать кнопку «Войти»
> 
> **Ожидаемый результат:** вход в систему не должен произойти. Должно появиться сообщение в нижнем тулбаре: “Неверный логин или пароль. Попробуйте ввести еще раз”.
> **Реальный результат:** приложение падает. После повторного открытия вы оказываетесь авторизованным под юзером, ник которого ввели
- [x] Исправлено:
     - теперь пользователь считается авторизованным после успешного сравнения публичного ключа

- [x] Проверено:

**Comment by Monserg** [comment]
> **Title-3:** не проходит авторизация с активным ключом
> 
> **Воспроизведение:**
> 1. Открыть приложение. 
> 2. Перейти на экран «Войти» 
> 3. Нажать кнопку «Войти с активным ключом»
> 4. Ввести существующий логин 
> 5. Ввести соответствующий введенному логину активный ключ 
> 6. Нажать кнопку «Войти»
> 
> **Ожидаемый результат:** должен произойти вход в приложение под аккаунтом юзера, данные которого вы ввели для входа
> **Реальный результат:** Появился текст «ошибка авторизации. Если повторится – попробуйте выйти и зайти в свой аккаунт»
- [x] Исправлено:
     - при маппинге списка ключей профиля пользователя для 'active key' использовались данные из поля для 'owner key'.

- [x] Проверено:
