### ISSUE TITLE
баги: Экран 2 Лента (Lenta)

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/golos-ios#45]

**Comment by Monserg** [comment]
> **Title-1:** не все аватарки отображаются в юзерпике
> 
> **Воспроизведение:**
> 
> 1. Открыть приложение 
> 2. Авторизоваться 
> 3. Нажать на любой пункт в баре для открытия ленты
> 
> **Ожидаемый результат:** юзерпик должен соответствовать дизайну. все юзерпики должны отображать аватарки юзеров
> **Реальный результат:** на многих постах в юзерпиках стоят стандартные картинки вместо их реальных аватарок

**Comment by Monserg** [comment]
> **Title-2:** не отображается репутация на юзерпиках
> 
> **Воспроизведение:**
> 
> 1. Открыть приложение 
> 2. Авторизоваться 
> 3. Нажать на любой пункт в баре для открытия ленты
> 
> **Ожидаемый результат:** репутация у юзерпика должна соответствовать дизайну
> **Реальный результат:** нет репутации на юзерпиках

- [x] Исправлено:
     - репутация добавлена во все виды постов.
- [x] Проверено:

**Comment by Monserg** [comment]
> **Title-3:** на всех постах отображается значок реблога
> 
> **Воспроизведение:**
> 
> 1. Открыть приложение 
> 2. Авторизоваться 
> 3. Нажать на любой пункт в баре для открытия ленты
> 
> **Ожидаемый результат:** у поста, который является реблогом, должна быть иконка реблога и юзернейм автора поста. если это не реблог, то иконки быть не должно.
> **Реальный результат:** на всех постах отображается "стрелочка" знакоч реблога, независимо от того реблог это или нет. если это реблог, то не отображается юзернейм автора поста.

- [x] Исправлено:
- [x] Проверено:

**Comment by Monserg** [comment]
> **Title-4:** не кликабельный юзернейм
> 
> **Воспроизведение:**
> 
> 1. Открыть приложение 
> 2. Авторизоваться 
> 3. Нажать на любой пункт в баре для открытия ленты
> 4. нажать на юзернейм автора какого-либо поста
> 
> **Ожидаемый результат:** должен открыться профиль того юзера, на юзернейм которого вы нажали
> **Реальный результат:** юзернейм не кликабельный

- [x] Исправлено:
     - добавлено замыкание на передачу имени выбранного пользователя;
     - проверено для всех видов постов, включая Блоги и Ответы в профиле пользователя.
- [x] Проверено:

**Comment by Monserg** [comment]
> **Title-5:** некорректно отображается значок темы и сам текст темы поста
> 
> **Воспроизведение:**
> 
> 1. Открыть приложение 
> 2. Авторизоваться 
> 3. Нажать на любой пункт в баре для открытия ленты 
> 4. Выбрать пост
> 
> **Ожидаемый результат:** тема в посте должна соответствовать первому тэгу поста.
> **Реальный результат:** некорректно отображается название темы (написано транслитом ) и значок темы.

- [x] Исправлено:
     - исправлено в другом Issue;
     - скрыл значение '$23.22' для кнопки 'upvote';
     - добавил отображение кол-ва 'children': если значение = 0 соответствующий значок не отображается.
- [x] Проверено:

**Comment by Monserg** [comment]
> **Title-6:** заголовок в посте не соответствует дизайну
> 
> **Воспроизведение:**
> 
> 1. Открыть приложение 
> 2. Авторизоваться 
> 3. Нажать на любой пункт в баре для открытия ленты 
> 4. Выбрать пост
> 
> **Ожидаемый результат:** заголовок в посте должен отображаться и должен соответствовать дизайну
> **Реальный результат:** заголовок не соответствует установленному дизайну

**Comment by Monserg** [comment]
> **Title-7:** превью поста некорректное при наличии в после фото
> 
> **Воспроизведение:**
> 
> 1. Открыть приложение 
> 2. Авторизоваться 
> 3. Нажать на любой пункт в баре для открытия ленты 
> 4. Выбрать пост
> 
> **Ожидаемый результат:** должна отображаться фотография в размере, который соответствует дизайну и должна быть кнопка для разворачивания поста прямо в ленте
> **Реальный результат:** большинство фото либо просто не отображаются в превью, либо закрыты картинкой-заглушкой. нет кнопки для разворачивания поста прямо в ленте.

**Comment by Monserg** [comment]
> **Title-8:** превью поста некорректное при наличии в после только текста
> 
> **Воспроизведение:**
> 
> 1. Открыть приложение 
> 2. Авторизоваться 
> 3. Нажать на любой пункт в баре для открытия ленты 
> 4. Выбрать пост
> 
> **Ожидаемый результат:** должны отображаться первые 120 символов поста, должна быть кнопка, которая разворачивает пост прямо в ленте
> **Реальный результат:** в таких постах вовсе нет превью. отображается просто заголовок. нет кнопки для разворачивания поста прямо в ленте

**Comment by Monserg** [comment]
> **Title-9:** кнопка upvote не выполняет своих функций. 
> 
> **Воспроизведение:**
> 
> 1. Открыть приложение 
> 2. Авторизоваться 
> 3. Нажать на любой пункт в баре для открытия ленты 
> 4. Выбрать пост
> 5. нажать на кнопку upvote 
> 
> **Ожидаемый результат:** если пост не лайкнут, то при нажатии на кнопку она должна сменить цвет на зеленый. если пост лайкнут, то при нажатии на кнопку она должна сменить цвет на серый. 
> **Реальный результат:** при нажатии на кнопку открывается пост

**Comment by Monserg** [comment]
> **Title-10:** кнопка комментариев не функциональна
> 
> **Воспроизведение:**
> 
> 1. Открыть приложение 
> 2. Авторизоваться 
> 3. Нажать на любой пункт в баре для открытия ленты 
> 4. Выбрать пост
> 5. нажать на кнопку комментариев
> 
> **Ожидаемый результат:** эта кнопка должна отображаться в соответствии с дизайном и при нажатии на нее должна открываться страница поста и проматываться сразу к разделу с комментариями
> **Реальный результат:** кнопка просто открывает пост.

**Comment by Monserg** [comment]
> **Title-11:** не отображается количество комментариев под постом
> 
> **Воспроизведение:**
> 
> 1. Открыть приложение 
> 2. Авторизоваться 
> 3. Нажать на любой пункт в баре для открытия ленты 
> 4. Выбрать пост
> 
> 
> **Ожидаемый результат:** Рядом с кнопкой комментариев должно отображаться количество комментариев к данному посту.
> **Реальный результат:** число не отображается

- [x] Исправлено:

- [x] Проверено:

**Comment by Monserg** [comment]
> **Title-12:** отсутствует плавающая кнопка "крестик" в нижнем правом углу
> 
> **Воспроизведение:**
> 
> 1. Открыть приложение 
> 2. Авторизоваться 
> 3. Нажать на любой пункт в баре для открытия ленты 
> 
> 
> **Ожидаемый результат:** кнопка должна отображаться в соответствии с дизайном (в нижнем правом углу). по нажатию на кнопку должен происходить переход на экран создания поста
> **Реальный результат:** кнопка не отображается

- [x] Исправлено:
     - в Альфе версии не реализовано.
- [x] Проверено:

**Comment by Monserg** [comment]
> **Title-13:** при скролинге лента зависает. время открытия поста большое
- [x] move to new Issue #57 (Title-2)

**Comment by Monserg** [comment]
> **Title-14:** некорректное отображение navbar.
> 
> **Воспроизведение:**
> 
> 1. Открыть приложение 
> 2. Авторизоваться 
> 3. зайти в ленту
> 
> 
> **Ожидаемый результат:** navbar должен соответствовать дизайну
> **Реальный результат:** navbar  отличается по цвету от statusbar. большое расстояние между пунктами navbar  "новое" и "промо". при оттягивании navbar  влево или вправо появляются большие отступы


> **Title-15:** кнопка «share» не функциональна
> 
> **Воспроизведение:**
> 
> 1. Открыть приложение 
> 2. Авторизоваться 
> 3. зайти в ленту
> 4. выбрать пост и нажать на нем кнопку «share»
> 
> 
> **Ожидаемый результат:**должно открыться окно, в котором отображены места, куда можно поделиться вашим постом
> **Реальный результат:** кнопка не функциональна


> **Title-16:** посты отображаются в неверном порядке 
> 
> **Воспроизведение:**
> 
> 1. открыть приложение
> 2. авторизоваться
> 3. открыть ленту
> 
> **Ожидаемый результат:** посты должны отображаться в том же порядке, что и на вебсайте golos.io
> **Реальный результат:** посты отображаются в неверном порядке

**Comment by Monserg** [comment]
> **Title-15:** кнопка «share» не функциональна
> 
> **Воспроизведение:**
> 
> 1. Открыть приложение 
> 2. Авторизоваться 
> 3. зайти в ленту
> 4. выбрать пост и нажать на нем кнопку «share»
> 
> 
> **Ожидаемый результат:**должно открыться окно, в котором отображены места, куда можно поделиться вашим постом
> **Реальный результат:** кнопка не функциональна
- [x] Исправлено:
     - в Альфа версии работы кнопки не реализована.
- [x] Проверено:

**Comment by Monserg** [comment]
> **Title-16:** посты отображаются в неверном порядке 
> 
> **Воспроизведение:**
> 
> 1. открыть приложение
> 2. авторизоваться
> 3. открыть ленту
> 
> **Ожидаемый результат:** посты должны отображаться в том же порядке, что и на вебсайте golos.io
> **Реальный результат:** посты отображаются в неверном порядке

- [x] Исправлено:

- [x] Проверено:
