### ISSUE TITLE
баги: Экран 4 Пост (Post)

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/golos-ios#46]
> **Title-1:** некорректное отображение поста

- [x] remove to new Issue #56 (Title-1)

**Comment by Monserg** [comment]
> **Title-2:** не все аватарки отображаются в юзерпике

- [x] remove to new Issue #57 (Title-1)

**Comment by Monserg** [comment]
> **Title-3:** не отображается репутация на юзерпиках
> 
> **Воспроизведение:**
> 
> 1.Открыть приложение
> 2.Авторизоваться
> 3.Нажать на любой пункт в баре для открытия ленты
> 4.открыть пост
> 
> **Ожидаемый результат:** репутация у юзерпика должна соответствовать дизайну
> **Реальный результат:** нет репутации на юзерпиках
- [x] Исправлено:
     - установил значение isHidden = false во всех местах, где используется значение репутации.
- [x] Проверено:

**Comment by Monserg** [comment]
> **Title-4:** на всех постах отображается значок реблога
> 
> **Воспроизведение:**
> 
> 1.Открыть приложение
> 2.Авторизоваться
> 3.Нажать на любой пункт в баре для открытия ленты
> 4.открыть пост
> 
> **Ожидаемый результат:** у поста, который является реблогом, должна быть иконка реблога и юзернейм автора поста. если это не реблог, то иконки быть не должно.
> **Реальный результат:** на всех постах отображается "стрелочка" значок реблога, независимо от того реблог это или нет. если это реблог, то не отображается юзернейм автора поста.
- [x] Исправлено:
     - во всех структурах добавил поле 'reblogged_by' (массив);
     - на экране Настроек добавил пункт 'Язык интерфейса';
     - исправил название темы в заголовке с 'ru--footografiya' -> 'фотография';
     - исправил работу реблога как в списках, так и в хедере при просмотре выбранного поста.
- [x] Проверено:

**Comment by Monserg** [comment]
> **Title-5:** не кликабельный юзернейм
> 
> **Воспроизведение:**
> 
> 1.Открыть приложение
> 2.Авторизоваться
> 3.Нажать на любой пункт в баре для открытия ленты
> 4.открыть пост
> 5.нажать на юзернейм автора поста
> 
> **Ожидаемый результат:** должен открыться профиль того юзера, на юзернейм которого вы нажали
> **Реальный результат:** юзернейм не кликабельный
- [x] Исправлено:
     - добавил переход на экран просмотра профиля автора поста при нажатии на его имя или автарки в хедере экрана просмотра выбранного поста.
- [x] Проверено:

**Comment by Monserg** [comment]
> **Title-6:** некорректно отображается значок темы и сам текст темы поста
> 
> **Воспроизведение:**
> 
> 1.Открыть приложение
> 2.Авторизоваться
> 3.Нажать на любой пункт в баре для открытия ленты
> 4.открыть пост
> 
> Ожидаемый результат: тема в посте должна соответствовать первому тэгу поста.
> Реальный результат: некорректно отображается название темы (написано транслитом ) и значок темы.
- [x] Исправлено:
     - теги не имеют изображений;
     - первый тег будет отображаться в виде иконки "решетка";
     - отображение тегов приведено в соответствие текущему языку интерфейса приложения.
- [x] Проверено:

**Comment by Monserg** [comment]
> **Title-7:** заголовок в посте не соответствует дизайну
> 
> **Воспроизведение:**
> 
> 1.Открыть приложение
> 2.Авторизоваться
> 3.Нажать на любой пункт в баре для открытия ленты
> 4.открыть пост
> 
> **Ожидаемый результат:** заголовок в посте должен отображаться и должен соответствовать дизайну
> **Реальный результат:** заголовок не соответствует установленному дизайну
- [ ] Исправлено:

- [ ] Проверено:

**Comment by Monserg** [comment]
> **Title-8:** шаринг поста не работает
> 
> **Воспроизведение:**
> 
> 1.Открыть приложение
> 2.Авторизоваться
> 3.Нажать на любой пункт в баре для открытия ленты
> 4.открыть пост
> 5. поделиться постом (например в телеграм)
> 
> **Ожидаемый результат:** пост должен отправиться адресату и корректно отображаться. по нажатию на нему пост должен открыться. 
> **Реальный результат:** отправляется шаблон 
- [x] Исправлено:
     - в Альфа версии не реализовано.
- [x] Проверено:

**Comment by Monserg** [comment]
> **Title-9:** кнопка выпадающего меню не функциональна
> 
> **Воспроизведение:**
> 
> 1.Открыть приложение
> 2.Авторизоваться
> 3.Нажать на любой пункт в баре для открытия ленты
> 4.открыть пост
> 5. нажать на кнопку выпадающего меню
> 
> **Ожидаемый результат:** должно открыться выпадающее меню
> **Реальный результат:** меню не открылось 
- [x] Исправлено:
     - в Альфа версии не реализовано.
- [x] Проверено:

**Comment by Monserg** [comment]
> **Title-7:** заголовок в посте не соответствует дизайну
- [x] remove to new Issue #56 (Title-2)
