### ISSUE TITLE
баги: Экран 5. Футтер поста. Не кликабельна кнопка upvote

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/golos-ios#47]
**Воспроизведение:**

1. Открыть приложение 
2. Авторизоваться 
3. Выбрать любой пост в ленте и нажать на него, пролистать до футтера 
4. Нажать на кнопку upvote

**Ожидаемый результат:** если лайк не стоит, то после нажатия кнопка должна сменить цвет на зеленый и рядом (справа от upvote) количество лайков должно увеличиться на единицу
**Реальный результат:** кнопка не кликабельна. количество лайков на посте не отображается

**Comment by Monserg** [comment]
- [x] Выполнено:
   - изменен алгоритм установки кол-ва Active Vote, а также соответствующей иконки;
   - добавлен АПИ 'Vote' со значениями weight = 1000/0;
   - добавлен alert view для информирования пользователя о результатах работы АПИ;
   - кол-во Active Vote изменяется по результатам выполнения АПИ;
   - при возврате на основной экран происходит обновление содержимого ячейки, соответствующей измененному посту.
