### ISSUE TITLE
баги: Экран 8. Профиль пользователя (Profile)

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/golos-ios#52]
**Title-1:** не открывается профиль по нажатию на юзернейм пользователя в посте

**Воспроизведение:**

1. Открыть приложение 
2. авторизоваться 
3. Открыть пост 
4. Нажать на юзернейм

**Ожидаемый результат:** должен открыться профиль того юзера, на юзернейм которого вы нажали
**Реальный результат**: профиль не открывается.
- [x] Исправлено:

- [x] Проверено:

**Comment by Monserg** [comment]
**Title-2:** профиль не открывается по нажатию на юзернейм из экрана комментариев

**Воспроизведение:**

1. Открыть приложение 
2. авторизоваться 
3. Открыть пост 
4. Перейти к комментариям 
5. Нажать на юзернейм одного из комментаторов

**Ожидаемый результат:** должен открыться профиль того юзера, на юзернейм которого вы нажали
**Реальный результат**: профиль не открывается.
- [x] Исправлено:
     - добавлен переход на экран профиля выбранного пользователя при нажатии на его аватарку, а также имя.
- [x] Проверено:

**Comment by Monserg** [comment]
**Title-3:** профиль не открывается по нажатию на юзернейм из экрана ленты

**Воспроизведение:**

1. Открыть приложение 
2. авторизоваться 
3. Нажать на юзернейм автора одного из постов

**Ожидаемый результат:** должен открыться профиль того юзера, на юзернейм которого вы нажали
**Реальный результат**: профиль не открывается.
- [x] Исправлено:

- [x] Проверено:

**Comment by Monserg** [comment]
**Title-4:** аватар юзера не отображается в юзерпике 

**Воспроизведение:**

1. Открыть приложение 
2. Авторизоваться 
3. Открыть какой-либо профиль

**Ожидаемый результат:** аватар должен отображаться в юзерпике
**Реальный результат**: аватар не отображается
- [ ] Исправлено:

- [ ] Проверено:

**Comment by Monserg** [comment]
**Title-5:** имя пользователя не отображается

**Воспроизведение:**

1. Открыть приложение 
2. Авторизоваться 
3. Открыть какой-либо профиль

**Ожидаемый результат:** имя юзера должно отображаться в профиле если оно было указано пользователем
**Реальный результат**: имя пользователя не отображается 
- [x] Исправлено:

- [x] Проверено:

**Comment by Monserg** [comment]
**Title-6:** не отображается кнопка "подписаться/отписаться"

**Воспроизведение:**

1. Открыть приложение 
2. Авторизоваться 
3. Открыть какой-либо профиль (не свой)

**Ожидаемый результат:** кнопка должна отображаться в профиле (в обложке). Если вы не подписаны на данного юзера – «подписаться», в противном случае «отписаться»
**Реальный результат**: кнопки нет
- [x] Исправлено:
     - в Альфа-версии не реализовано.
- [x] Проверено:

**Comment by Monserg** [comment]
**Title-7:** отсутствует поле об авторе 

**Воспроизведение:**

1. Открыть приложение 
2. Открыть какой-либо профиль (не свой)

**Ожидаемый результат:** если пользователь указывал информацию «о себе», то данный раздел должен идти сразу после обложки
**Реальный результат**: поле об авторе отсутствует
- [x] Исправлено:
     - открыл для просмотра соответствующее поле.
- [x] Проверено:

**Comment by Monserg** [comment]
**Title-8:** некорректно отображается закладка "ответы"

**Воспроизведение:**

1. Открыть приложение 
2. Открыть какой-либо профиль 

**Ожидаемый результат:** закладка должна отображаться в соответствии с дизайном
**Реальный результат**: закладка обрезана. отображается только часть слова "отв"
- [x] Исправлено:
     - название отображается полностью.
- [x] Проверено:

**Comment by Monserg** [comment]
**Title-9:** при обновлении ленты ответов в закладке "ответы" приложение падает

**Воспроизведение:**

1. Открыть приложение 
2. Открыть какой-либо профиль 
3. перейти в закладку "ответы"
4. обновить ленту с ответами потянув ленту вниз

**Ожидаемый результат:** лента с ответами должна обновиться
**Реальный результат**: приложение падает
- [x] Исправлено:
     - исправил код в файле PostFeedTableViewCell.
- [x] Проверено:

**Comment by Monserg** [comment]
**Title-10:** если ответить на комментарий в формате "@joseph.kalu комментарий", то в ответах будет отображаться некорректно

**Воспроизведение:**

1. Открыть приложение 
2. Открыть какой-либо профиль 
3. ответить на комментарий в формате "@joseph.kalu комментарий"
4. открыть на этом же профиле вкладку "ответы"

**Ожидаемый результат:** ваш ответ должен отображаться в виде "@joseph.kalu комментарий"
**Реальный результат**: отображается в виде "[joseph.kalu](@joseph.kalu) комментарий"
- [ ] Исправлено:

- [ ] Проверено:

**Comment by Monserg** [comment]
**Title-11:** большие отступы между юзернеймом, текстом "ответил на ваш" и "комментарий/пост"

**Воспроизведение:**

1. Открыть приложение 
2. Открыть какой-либо профиль 
3. открыть закладку "ответы"

**Ожидаемый результат:** ответы должны соответствовать дизайну
**Реальный результат**: большие отступы между юзернеймом, текстом "ответил на ваш" и "комментарий/пост" (см. дизайн)
- [x] Исправлено:
     - изменил значения для Content Hugging Priority.
- [x] Проверено:

**Comment by Monserg** [comment]
**Title-12:** в закладке "посты" отображается только последних 10 постов

**Воспроизведение:**

1. Открыть приложение 
2. Открыть какой-либо профиль 
3. открыть закладку "посты"

**Ожидаемый результат:** должны отображаться все посты профиля
**Реальный результат**: отображаются только последние 10 постов профиля
- [x] Исправлено:
     - исправил ошибку в параметрах, которые передаются в АПИ на запрос списка ответов;
     - то же самое проделал для списка постов.
- [x] Проверено:

**Comment by daryasattarova** [comment]
Не исправлено: Title-4. Уточнение по поводу Title-5
