### ISSUE TITLE
баги: Экран 3.  Создать пост (Add post - text)

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/golos-ios#55]

**Comment by Monserg** [comment]
> **Title-1:** некорректное сообщение при попытке создать пост без тела
> 
> **Воспроизведение:**
> 
> 1. открыть приложение 
> 2. открыть окно создания поста
> 3. написать заголовок, тег
> 4. нажать кнопку создания поста
> 
> **Ожидаемый результат:** должно выдать сообщение "напишите текст"
> **Реальный результат:** сообщение с текстом "Assert Exception (10) body.size() > 0: Body is empty"

- [x] Исправлено: для элемента UITextView были разделены placeholder & text, проверка на пустое значение осталась для placeholder; перенес проверку в поле text; проверил - отображается сообщение в читаемом виде

- [x] Проверено

**Comment by Monserg** [comment]
> **Title-2:** кнопка создания жирного текста не активна
> 
> **Воспроизведение:**
> 
> 1. открыть приложение 
> 2. открыть окно создания поста
> 3. нажать на поле ввода тела
> 4. нажать на кнопку "В" на клавиатуре для жирного текста
> 
> **Ожидаемый результат:** должен включиться режим написания жирного текста
> **Реальный результат:** кнопка не активна

- [x] Исправлено: в Альфа версии предусмотрены только 2 кнопки

- [x] Проверено

**Comment by Monserg** [comment]
> **Title-3:** заголовок не приводится автоматически к требуемому виду
> 
> **Воспроизведение:**
> 
> 1. открыть приложение 
> 2. открыть окно создания поста
> 3. написать заголовок
> 
> **Ожидаемый результат:** в процессе написания тег должен приводиться к требуемому виду (судя по всему первая буква должна быть заглавной, остальные строчные. то есть заголовок не должен быть написан капсом)
> **Реальный результат:** заголовок можно написать капсом

- [x] Исправлено: набор текста производится удобным для пользователя способом; любые преобразования, принятые в системе, выполняются непосредственно перед формированием АПИ и скрыты от просмотра.

- [x] Проверено

**Comment by Monserg** [comment]
> **Title-4:** ошибка при создании поста с пустым тегом
> 
> **Воспроизведение:**
> 
> 1. открыть приложение 
> 2. открыть окно создания поста
> 3. ввести заголовок, тело
> 4. ввести тег, потом нажав на него отредактировать (удалить все символы из него)
> 5. нажать кнопку создания поста
> 
> **Ожидаемый результат:** должно выдать сообщение "некорректный тег"
> **Реальный результат:** выдает сообщение "Assert Exception (10) permlink.size() > STEEMIT_MIN_PERMLINK_LENGTH && permlink.size() < STEEMIT_MAX_PERMLINK_LENGTH: Permlink is not a valid size"

- [x] Исправлено: к существующим проверкам добавлена еще одна - на isEmpty; проверено - работает: в случае нажатия пробела и попытки создать новый пост пользователь увидит сообщение с предложением ввести название темы.

- [x] Проверено

**Comment by Monserg** [comment]
> - [] **Title-5:** ошибка при попытке добавление тега со спец символами
> **Воспроизведение:**
> 
> 1. открыть приложение 
> 2. открыть окно создания поста
> 3. ввести заголовок, тело
> 4. ввести тег, например "&$%" и нажать кнопку создания поста
> 
> **Ожидаемый результат:** должно быть сообщение с текстом "некорректный тег"
> **Реальный результат:** выдает ошибку например "Assert Exception (10) false: Invalid permlink character: &"

-

**Comment by Monserg** [comment]
> **Title-6:** тема пишется транслитом
> 
> **Воспроизведение:**
> 
> 1. открыть приложение 
> 2. открыть окно создания поста
> 3. создать пост, добавив теги
> 
> **Ожидаемый результат:** теги должны отображаться в том формате, в котором были созданы
> **Реальный результат:** если создать пост с приложения, то тег будет написан транслитом. если пост был создан с вэб, приложение его отображает в виде "ru--testteg" например (то есть всегда идет приставка ru--)

- [x] Исправлено: в библиотеке GoloSwift создана функция, которая преобразует текст Latin -> Cyrillic; проверил в работе при просмотре выбранного Поста из любого списка.

- [x] Проверено

**Comment by Monserg** [comment]
> - [ ] **Title-7:** приложение вылетает если редактировать тег со смайлами. приложение не создает пост с тегов, в котором есть смайл
> 
> **Воспроизведение:**
> 
> 1. открыть приложение 
> 2. открыть окно создания поста
> 3. ввести заголовок, тело
> 4.ввести в тег эмоджи и нажать кнопку создания поста/ввести в тег эмоджи и попробовать удалить один эмоджи из этого тега
> 
> **Ожидаемый результат:** должно выдать сообщение "некорректный тег"
> **Реальный результат:** если нажать кнопку создания поста, то ничего не будет происходить. если редактировать тег, то приложение упадет

- уточнение: смайлики в тегах не поддерживаются?!

**Comment by Monserg** [comment]
> **Title-8:** при попытке создания поста с уже существующим заголовком отображается нечитабельное сообщение об ошибке
> 
> **Воспроизведение:**
> 
> 1. открыть приложение 
> 2. открыть окно создания поста
> 3. ввести заголовок, который был ранее использован в ваших постах
> 
> **Ожидаемый результат:** пост должен создаться
> **Реальный результат:** либо пишет "пост успешно создан", но пост не создается. либо ошибку выдает "Assert Exception (10) equal(com.parent_permlink, o.parent_permlink): The permlink of a comment cannot change"

- [x] Исправлено:
     - внесены правки на стороне библиотеки GoloSwift;
     - перед запуском основного АПИ на создание поста проверяется наличие поста с аналогичным 'permlink': в случае положительного ответа автоматически добавляется timestamp;
     - исправлена ошибка маппинга ответа по полю 'result'.
- [x] Проверено

**Comment by Monserg** [comment]
> **Title-9:** при открытии клавиатуры экран не скролится. клавиатура закрывает теги
> 
> **Воспроизведение:**
> 
> 1. открыть приложение 
> 2. открыть окно создания поста
> 3. нажать на любое поле ввода
> 
> **Ожидаемый результат:** экран должен скролиться чтобы можно было получить доступ к любому элементы на экране
> **Реальный результат:** экран не скролится. клавиатура при открытии закрывает теги

- [x] Уточнения:
     - актуально для модели iPhone 5s, взял в работу на исправление


- [x] Исправлено:

- [x] Проверено

**Comment by Monserg** [comment]
> - [ ] **Title-11:** (не могу стабильно пока воспроизвести) ошибка при сворачивании и разворачивании приложения
> 
> **Воспроизведение:**
> 
> 1. открыть приложение 
> 2. зайти на какой-либо экран (например создания поста)
> 3. свернуть приложение и через какое-то время развернуть
> 
> **Ожидаемый результат:** должен открыться тот же экран
> **Реальный результат:** периодически вижу сообщение с текстом "Assert Exception (10) now <trx.expiration:" либо "Assert Exception (10) (skip & skip_transaction_dupe_check) || trx.idx.indices().get<by_trx_id>().find(trx_id) == trx_idx.incices().get<by_trx_id>().end(): Duplicate transaction check failed"

-

**Comment by Monserg** [comment]
> - [ ] **Title-12:** (не могу стабильно пока воспроизвести) ошибка при постинге ссылки и фото
> 
> **Воспроизведение:**
> 
> 1. открыть приложение 
> 2. открыть окно создания поста
> 3. написать заголовок, тег
> 4. добавить ссылку и фото и нажать кнопку создания поста
> 
> **Ожидаемый результат:** пост должен создаться
> **Реальный результат:** периодически вижу сообщение с текстом "Assert Exception (10) equal(com.parent_permlink, o.parent_permlink): The permlink of a comment cannot change"

-
