### ISSUE TITLE
баги: Заголовок в посте не соответствует дизайну

### ISSUE THREAD

**Issue by Monserg** [GolosChain/golos-ios#56]
> **Воспроизведение:**
> 
> 1.Открыть приложение
> 2.Авторизоваться
> 3.Нажать на любой пункт в баре для открытия ленты
> 4.открыть пост
> 
> **Ожидаемый результат:** заголовок в посте должен отображаться и должен соответствовать дизайну
> **Реальный результат:** заголовок не соответствует установленному дизайну
> **Версия билда: 1.0.16**
- [x] Исправлено:
     - задача - реализовать адаптивную верстку для текстовки и комментариев. Иными словами, реализовать поддержку форматирования для элемента управления WKWebView.
- [x] Проверено:

**Comment by Monserg** [comment]
> **Title-1:** некорректное отображение поста
> 
> **Воспроизведение:**
> 
> 1. открыть приложение
> 2. авторизоваться
> 3. открыть пост, например https://golos.io/ru--dobryijkit/@dobryj.kit/dobrootchet-o-raspredelenii-vyplat-silami-dobrogo-kita-za--16-08-2018g-20180816t150858457z
> 
> **Ожидаемый результат:** пост должен отображаться корректно и отображать корректно всю информацию
> **Реальный результат:** некорректно отображается информация в посте (приведен пример поста в пункте 3 воспроизведения)
- [ ] Исправлено:
     - исправлен баг с отображением списка тегов, выходящих за пределы UICollectionView;
     -
- [ ] Проверено:

**Comment by Monserg** [comment]
> **Title-2:** заголовок в посте не соответствует дизайну
> 
> **Воспроизведение:**
> 
> 1.Открыть приложение
> 2.Авторизоваться
> 3.Нажать на любой пункт в баре для открытия ленты
> 4.открыть пост
> 
> **Ожидаемый результат:** заголовок в посте должен отображаться и должен соответствовать дизайну
> **Реальный результат:** заголовок не соответствует установленному дизайну
- [ ] Исправлено:
     - задача - реализовать адаптивную верстку для текстовки и комментариев. Иными словами, реализовать поддержку форматирования для элемента управления WKWebView.
- [ ] Проверено:

**Comment by daryasattarova** [comment]
**Правка!** Данная задача реализована, но требуется также поправить заголовки постов в ленте по такому же принципу 

- [x] Исправлено:
     - удалил использование коэффициента widthRatio для шрифтов.
- [ ] Проверено:
