### ISSUE TITLE
баги: Не все аватарки отображаются в юзерпике

### ISSUE THREAD

**Issue by Monserg** [GolosChain/golos-ios#57]
> **Воспроизведение:**
> 
> 1.Открыть приложение
> 2.Авторизоваться
> 3.Нажать на любой пункт в баре для открытия ленты
> 4.открыть пост
> 
> **Ожидаемый результат:** юзерпик должен соответствовать дизайну. все юзерпики должны отображать аватарки юзеров
> **Реальный результат:** на многих постах в юзерпиках стоят стандартные картинки вместо их реальных аватарок
- [x] Исправлено:

- [ ] Проверено:

**Comment by Monserg** [comment]
> **Title-1:** не все аватарки отображаются в юзерпике (move from Issue #46)
> 
> **Воспроизведение:**
> 
> 1.Открыть приложение
> 2.Авторизоваться
> 3.Нажать на любой пункт в баре для открытия ленты
> 4.открыть пост
> 
> **Ожидаемый результат:** юзерпик должен соответствовать дизайну. все юзерпики должны отображать аватарки юзеров
> **Реальный результат:** на многих постах в юзерпиках стоят стандартные картинки вместо их реальных аватарок
- [ ] Исправлено:

- [ ] Проверено:

**Comment by Monserg** [comment]
> **Title-2:** при скролинге лента зависает. время открытия поста большое (move from Issue #45)
> 
> **Воспроизведение:**
> 
> 1. Открыть приложение 
> 2. Авторизоваться 
> 3. Нажать на любой пункт в баре для открытия ленты 
> 4. поскролить ленту
> 5. открыть пост
> 
> 
> **Ожидаемый результат:** лента должна быстро скролиться без зависаний. пост должен открываться сразу после запроса на открытие.
> **Реальный результат:** при скролинге лента зависает периодически на несколько секунд. по нажатию на пост, пост открывается больше чем через 10 секунд. работа не асинхронная.

- [ ] Исправлено:

- [ ] Проверено:

**Comment by daryasattarova** [comment]
![image](https://user-images.githubusercontent.com/42342756/45353102-ab7a4500-b5c2-11e8-83d5-a14be3ca8734.png)
![image](https://user-images.githubusercontent.com/42342756/45353156-cfd62180-b5c2-11e8-9e3c-7639ec40b47b.png)
Проблема не решена!

**Comment by Monserg** [comment]
- [x] Тестирование:
     - на симуляторе iPhone 5s - 12.0;
     - iPhone 7 - 12.0 (mode: Debug & Release).
