### ISSUE TITLE
Число комментариев не соответствует действительности

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/golos-ios#70]
**Воспроизведение:** 
1. открыть приложение
2. авторизоваться
3. перейти в ленту в постами
4. выбрать пост

**Ожидаемый результат:** число комментариев под постом должно соответствовать действительности
**Реальный результат:** число комментариев не соответствует реальному числу

**Comment by Monserg** [comment]
- [x] исправлено: добавил очистку переиспользуемой ячейки для отображения поста в списке.
