### ISSUE TITLE
не работает постинг

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/golos-ios#71]
**Воспроизведение:**
1. открыть приложение
2. авторизоваться
3. нажать на таббаре кнопку "+"
4. заполнить все необходимые поля
5. нажать кнопку создания поста

**Ожидаемый результат:** должно появиться сообщение об успешном создании поста и созданный пост должен отобразиться в профиле
**Реальный результат:** пост не создается. при нажатии кнопки создания поста ничего не происходит 
**Комментарий:** были случаи, при нажатии кнопки создания поста приложение вылетало. при повторном открытии приложения пост был опубликован

**Comment by Monserg** [comment]
- [x] Исправлено:
     - см. #75
