### ISSUE TITLE
Приложение падает после смены языка из приложения на английский

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/golos-ios#72]
**Воспроизведение:**
1. открыть приложение
2. авторизоваться
3. перейти в профиль и открыть настройки
4. (при условии, что язык установлен русский) сменить язык приложения на английский
5. открыть ленту

**Ожидаемый результат:** приложение в целом должно сменить локализацию на английскую
**Реальный результат:** приложение падает и больше не открывается

**Comment by Monserg** [comment]
- [x] Исправлено:
     - приложение падало в результате ошибки работы функции по очистке кэша;
     - функция отключена и ее исправление вынесено в отдельный Issue;
     - работа приложения в указанном кейсе проверена на симуляторах iPhone 5s & 8.
