### ISSUE TITLE
При смене языка с русского на английский, названия лент остаются на русском

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/golos-ios#73]
**Предусловие:** приложение должно иметь русскую локализацию

**Воспроизведение:**
1. открыть приложение
2. авторизоваться
3. открыть профиль
4. перейти в настройки и сменить язык с русского на английский
5. перейти на экран с лентами

**Ожидаемый результат:** названия лент должны быть переведены на английский язык
**Реальный результат:** названия лент остаются на русском

**Comment by Monserg** [comment]
- [ ] Исправлено:
     - на основном экране (дальше - по всему проекту) удалил стороннюю библиотеку SJSegmentedScrollView;
     - создал кастомный элемент управления согласно дизайна;
     - проверил его работу при смене языка интерфейса в Настройках: поддерживаются 2 языка - русский и английский;
     - перенес кастомные элемент управления на экран профиля пользователя - переключение между списками постов и ответов.
