### ISSUE TITLE
приложение вылетает при нажатии на значок комментария

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/golos-ios#81]
Воспроизведение:
1. открыть приложение
2. авторизоваться
3. зайти на профиль
4. нажать значок комментария

Ожидаемый результат: должен открыться пост и проскролить до комментариев
Реальный результат: приложение вылетает

**Comment by Monserg** [comment]
- [x] Исправлено:
     - в предыдущем биде была создана новая структура для работы с выбранными постами во всех списках;
     - при внесении изменений остались ссылки на неиспользуемый тип данных;
     - исправление заключается в переходе во всем коде на новый тип данных для выбранных постов;
     - работа приложения проверена на симуляторе и iPhone 7.

**- При нажатии на значок комментария в открытом посте приложение вылетает**

**Comment by Monserg** [comment]
- [ ] Исправлено:
     - при нажатии на кнопку комментария открывается окно просмотра выбранного поста и автоматически выполняется скроллинг до раздела с комментариями.
