### ISSUE TITLE
поменять местами ленты

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/golos-ios#85]
Экран Лента
Воспроизведение:
1. открыть приложение
2. авторизоваться
3. перейти в ленты 

Ожидаемый результат: увидеть список лент Лента, Новое, Актуальное, Популярное, Промо
Реальный результат: отображение списка лент в другом порядке

**Comment by Monserg** [comment]
- [x] Исправлено:
     - поменял местами списки постов.
