### ISSUE TITLE
В Альфа версии скрыть цифру рейтинга на юзерпике

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/golos-ios#86]
Воспроизведение:
1. открыть приложение
2. авторизоваться
3. перейти в ленты, профиль, комментарии, хедер и футер поста  

Ожидаемый результат: цифры рейтинга у юзерпика не должны отображаться в альфа версии приложения в лента, профиле, комментария, хедере и футере поста  
Реальный результат: у юзерпика отображается цифра рейтинга пользовтаеля

**Comment by Monserg** [comment]
- [ ] Исправлено:
     - срыл рейтинг в PostFeedHeaderView;
     -
