### ISSUE TITLE
PostFooter: убрать кнопку продвинуть пост и отблагодарить за пост в текущей версии

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/golos-ios#88]
Воспроизведение:
1. открыть приложение
2. авторизоваться
3. перейти в ленты
4. открыть пост 
5. перейти в футер поста  

Ожидаемый результат: кнопки продвинуть пост и отблагодарить за пост не должно быть в альфа версии приложения
Реальный результат: в футоре поста отображаются нерабочие кнопки продвинуть пост и отблагодарить за пос

**Comment by Monserg** [comment]
- [x] Исправлено:
     - скрыл представление buttonsStackView на экране PostShow;
     - изменил Top constraint для представления backgroundGrayViewsCollection.
