### ISSUE TITLE
PostFooter: убрать блог подписаться на тег

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/golos-ios#90]
Воспроизведение:
1. открыть приложение
2. авторизоваться
3. перейти в ленты  
4. открыть пост
5. перейти в футер
6. нажать кнопку подписаться на тег

Ожидаемый результат: блока и кнопки подпистаься на тег не должно быть в альфа версии приложения
Реальный результат: отображается блог подпистаься на тег, по тапу на кнопку предупреждение -инфо в разработке

**Comment by Monserg** [comment]
- [x] Исправлено:
     - скрыл представление Subscribe Topic View на экране PostShow;
     - уменьшил высоту элемента Subscribe Stack View в 2 раза со 180 до 90px.
